### ISSUE TITLE
Tabs block

### ISSUE THREAD

**Issue by rofe** [hlxsites/mmm-af#10]
Add a tabs block like on [this page](https://mymoneymatters.alexforbes.com/starting.html#financialfuture)

**Comment by rofe** [comment]
Great! I would make the block name more explicit, so it's more natural for the author to type in word:
`Vertical Tabs` -> `vertical-tabs`
or just
`Tabs` -> `tabs` (I didn't see any horizontal tabs on the site 😉)

**Comment by sdmcraft** [comment]
> Great! I would make the block name more explicit, so it's more natural for the author to type in word: `Vertical Tabs` -> `vertical-tabs` or just `Tabs` -> `tabs` (I didn't see any horizontal tabs on the site 😉)

Yes that sounds better. I renamed it to `tabs`
