### ISSUE TITLE
PDF handling

### ISSUE THREAD

**Issue by rofe** [hlxsites/mmm-af#3]

**Comment by rofe** [comment]
Depends on
- https://github.com/adobe/helix-admin/pull/706
- https://github.com/adobe/helix-sidekick/pull/325
- https://github.com/adobe/helix-sidekick-extension/pull/115

**Comment by sdmcraft** [comment]
For now, the pdfs have been added to https://github.com/hlxsites/mmm-af/tree/main/assets/pdf . Consider revisiting once pdf support lands in content-bus.
